# Summarize This {#summarize-this}

#### Keywords {-}

summarize, abstract, save time, NLP

## Reading... In pursuit of more and better
Today, with our busy lives, finding the time to read has become a prominent challenge. For web surfers, one study concluded that people read at most 28% of the words during an average visit [@nielsen_how_nodate]. Another study examined the time spent on every page and determined that 55% of users read five seconds or less [@read_55_2016]. With such lack of appetite for long readings, two third of Americans rely today on social media to getting their news [@wagner_two-thirds_2017]. While social media was able to deliver "fast" and "quick" information, sometimes in 140 characters or less, it lacks the depth and breadth that is usually needed to digest complex topics. When it comes to news, social media is the new news agency, 

## Success = Time X Quality

There is a golden opportunity for a solution that can balance between time and quality. I believe there is a segment of users, who are hungry for a quality readings but have limited time. This tool is for them.

The idea is an online tool that can process lengthy articles and extract the important words and sentences to generate a concise summary in few paragraphs. This tool will solve for "time" and "quality" simultaneously. The success of this tool is the product of time and summary quality, therefore we’ll need to continuously measure, test and experiment the quality. Since we have no control over time, the quality will be our path to success.

-- TODO: Similar studies.

## How will this work

The output of the tool is a summarized version that can be read in relatively short time. This tool applies state of the art Natural Language Processing (NLP) models to remove redundant and common English words and then determines important words based on the frequency of appearance. We assume that the important sentences will be the sentences where important words appeared.

As previously said, the success of this tool is contingent upon the quality of the produced summary, i.e., is it too short to understand the topic? Is it too precise that essential information is excluded? Is it still very long? 

The success can be measured in multiple ways: 

1. Engagement Score: A formula that can be measured through various variables, such as how often existing users of the system use the tool and if their usage pattern is trending up.

2. New User SignUp: A side-effect of the engagement score that can be measured by analyzing new users trend, which could be a result of the spread of word of mouth.

3. Implicit Feedback: Measuring how long user session lasts.  

4. Explicit Feedback: Enabling a thumbs-up, thumbs-down rating with every summary. We will use the results to help us revise and tune the summary. We will also run NPS survey, which is a great way to measure the value the tool is delivering to the users.

5. A/B Experiment: Using different models to summarize long articles and picking the best model based on the collected implicit and explicit feedback.

## The Difference
This will be very useful for anyone seeking to acquire knowledge and information in a short period. Rather than turning away lengthy articles or books, we believe this tool will encourage users to read and learn more.
